openapi: 3.0.0
info:
  version: 0.0.1
  title: basic
paths:
components:
  schemas:
    PrimitiveString:
      type: string
    StringDefault:
      type: string
      default: foo
    StringDesc:
      type: string
      description: description
    StringMail:
      type: string
      format: email
    StringUrl:
      type: string
      format: uri
    StringUuid:
      type: string
      format: uuid
    StringRange:
      type: string
      minLength: 10
      maxLength: 20
    StringPattern:
      type: string
      pattern: '[a-z]+'
    PrimitiveNumber:
      type: number
    NumberMulitplier:
      type: number
      multipleOf: 2
    NumberRange:
      type: number
      minimum: 0
      maximum: 100
    NumberRangeExclusive:
      type: number
      minimum: 0
      exclusiveMinimum: true
      maximum: 100
      exclusiveMaximum: true
    PrimitiveInteger:
      type: integer
    PrimitiveBoolean:
      type: boolean
    NullablePrimitive:
      type: string
      nullable: true
    Array:
      type: array
      items:
        type: string
    ArrayRange:
      type: array
      items:
        type: string
      minItems: 1
      maxItems: 10
    ArrayLength:
      type: array
      items:
        type: number
      minItems: 3
      maxItems: 3
    # 'uniqueItems' not supported
    NullableArray:
      type: array
      items:
        type: number
      nullable: true
    StringEnum:
      type: string
      enum:
        - alpha
        - beta
    NumberEnum:
      type: number
      enum:
        - 1.2
        - 34.5
    IntegerEnum:
      type: integer
      enum:
        - 12
        - 345
    NullableEnum:
      type: string
      enum:
        - alpha
        - beta
      nullable: true
    SingleEnum:
      type: integer
      enum:
        - 100
    NonArrayEnum:
      type: integer
      enum: 1000
    TotallyObject:
      type: object
      properties:
        StringProp:
          type: string
        NumberProp:
          type: number
    # 'minProperties' and 'maxProperties' are not supported
    MaybeObject:
      properties:
        IntegerProp:
          type: integer
        StringArrayProp:
          type: array
          items:
            type: string
    NullableObject:
      type: object
      properties:
        BooleanProp:
          type: boolean
        StringEnumProp:
          type: enum
          enum:
            - delta
            - gamma
      nullable: true
    AllOfObjects:
      allOf:
        - type: object
          properties:
            FooProp:
              type: string
            BarProp:
              type: string
        - type: object
          properties:
            HogeProp:
              type: string
            FugaProp:
              type: string
    AllOfObjectRefs:
      allOf:
        - $ref: '#/components/schemas/TotallyObject'
        - $ref: '#/components/schemas/MaybeObject'
    AllOfMixed:
      allOf:
        - $ref: '#/components/schemas/TotallyObject'
        - type: object
          properties:
            FooProp:
              type: string
            BarProp:
              type: string
    AllOfInclNonObject:
      allOf:
        - $ref: '#/components/schemas/TotallyObject'
        - $ref: '#/components/schemas/PrimitiveString'
        - $ref: '#/components/schemas/MaybeObject'
    AllOfNone:
      allOf:
    AnyOfSingle:
      anyOf:
        - $ref: '#/components/schemas/TotallyObject'
    AnyOfMultiple:
      anyOf:
        - $ref: '#/components/schemas/TotallyObject'
        - $ref: '#/components/schemas/MaybeObject'
    AnyOfNone:
      anyOf:
    OneOfSingle:
      oneOf:
        - $ref: '#/components/schemas/TotallyObject'
    OneOfMultiple:
      oneOf:
        - $ref: '#/components/schemas/TotallyObject'
        - $ref: '#/components/schemas/MaybeObject'
    OneOfNone:
      oneOf:
