openapi: 3.0.0
info:
  version: 1.0.0
  title: sample
paths:
components:
  schemas:
    String:
      type: string
      minLength: 10
      maxLength: 20
      pattern: '[a-z]+'
      nullable: true
      default: foo
    String2:
      type: string
      minLength: 10
      maxLength: 20
      pattern: '[a-z]+'
      nullable: true
    String3:
      type: string
      minLength: 10
      maxLength: 20
      pattern: '[a-z]+'
      default: foo
    Hoge:
      type: object
      properties:
        A:
          $ref: '#/components/schemas/String'
        B:
          $ref: '#/components/schemas/String2'
        D:
          $ref: '#/components/schemas/String3'
    Fuga:
      type: object
      properties:
        A:
          type: object
          properties:
            A1:
              $ref: '#/components/schemas/String'
            A2:
              type: object
              required:
                - A4
              properties:
                A3:
                  $ref: '#/components/schemas/String2'
                A4:
                  $ref: '#/components/schemas/String3'
        B:
          $ref: '#/components/schemas/String2'
        D:
          $ref: '#/components/schemas/String3'
    StringMail:
      type: string
      format: email
    StringUrl:
      type: string
      format: uri
    StringUuid:
      type: string
      format: uuid
